### ISSUE TITLE
[Pro] Cron syntax is wrong

### ISSUE THREAD

**Issue by jeromepin** [dbacked/agent#4]
According to both the cron syntax and [crontab.guru](https://crontab.guru/#0_*_*_*_*), `0 * * * * *` means "Every hour at the minute 0" (i.e 1h00, 2h00, etc...).

But the UI tells "Every minute" :

![UI](https://i.imgur.com/ZwBImbI.png)

Indeed, the 3 buttons seems to be broken too : 

- "Everyday at midnight" is `0 0 0 * * *` but should be `0 0 * * *`
- "Every two days at midnight" is `0 0 0 */2 * *` but should be `0 0 */2 * *`
- "Every monday at midnight" is `0 0 0 * * 1` but should be `0 0 * * 1`

This is due to an incorrect number of fields. Cron needs 5 fields and there is 6.

Am I missing something ?

**Comment by geekuillaume** [comment]
Thanks for the report, I've fixed the error.
