### ISSUE TITLE
Can't uninstall

### ISSUE THREAD

**Issue by grounded-warrior** [dbacked/agent#7]
this is causing constant memory spikes on my server and I can't seem to get it uninstalled, please provide some guidance, thanks

**Comment by geekuillaume** [comment]
Thanks for the feedback. The memory spikes are normal but shouldn't be big (max 200MB for a big database). Are you running the agent on a small server?

The uninstall process is not yet automated but it's quite easy to manually delete it. I've added a documentation page [here](https://dbacked.github.io/agent/guide/uninstall.html) to explain how to do it.
